<?php

/**
 * @file
 * Contains next_service.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function next_service_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the next_service module.
    case 'help.page.next_service':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
