<?php

/**
 * @file
 * Contains next_service.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function next_service_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the next_service module.
    case 'help.page.next_service':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for node entity type.
 */
function next_service_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
  // Only if node is worklog.
  if ($entity->bundle() == 'worklog') {
    $ns->updateDevice($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update() for node entity type.
 */
function next_service_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  // Only if node is worklog.
  if ($entity->bundle() == 'worklog') {
    $ns->updateDevice($entity);
  }
}
